# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-22 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afcon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Angola',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Cameroon',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Egypt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Nigeria',
        ),
        migrations.AddField(
            model_name='post',
            name='fact',
            field=models.CharField(default='Test', max_length=50),
        ),
    ]
